name: Auto Commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1-15 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check repository
        uses: actions/checkout@v2
        with:
           ref: master
      
      - name: Create file and commit
        run: |
          FILE="richest_people.txt"
          if [ ! -f "$FILE" ]; then
            echo "Creating $FILE" > "$FILE"
            echo "commit:1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP 'commit:\K\d+' "$FILE")
            if [ -z "$CURRENT_COUNT" ]; then
              CURRENT_COUNT=0
            fi
            NEW_COUNT=$((CURRENT_COUNT + 1))
            sed -i "s/commit:$CURRENT_COUNT/commit:$NEW_COUNT/" "$FILE"
          fi
          git config --global user.name "IllalRajinCoding"
          git config --global user.email "roxyuciha@gmail.com"
          git add "$FILE"
          git commit -m "Auto commit: Updated $FILE"
          git push origin master
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}