name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 * * *" # Every hour from 1 AM to 3 PM daily'

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > richest_last_update.txt

      - name: Commit files changes
        run: |
          git config --global --add safe.directory /github/workspace
          git config --local user.name 'Robbanie'
          git config --local user.email 'roxyuciha@gmail.com'
          # Use the timestamp written in the previous step for the commit message
          d=$(cat richest_last_update.txt || true)
          git add richest_last_update.txt
          git commit -m "Auto update last update time to $d" || echo "No changes to commit"

      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
