name: Auto Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1-15 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # penting agar bisa push dengan GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update timestamp file
        id: set_time
        run: |
          d=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          echo "$d" > richest_last_update.txt
          echo "time=$d" >> "$GITHUB_OUTPUT"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add richest_last_update.txt
          git commit -m "Auto update: ${{ steps.set_time.outputs.time }}" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:main
